import { assertType, expect, expectTypeOf, test } from 'vitest';
import { router } from './router';
import { z } from 'zod';

test('Should generate mutation route', () => {
  const route = router.mutation('/post/delete/{id}', {
    input: z.object({ id: z.string() }),
    output: {
      BAD_REQUEST: z.object({
        message: z.string(),
      }),
    },
  });

  expect(route.type).toBe<typeof route.type>('mutation');
  expectTypeOf(route.path).toMatchTypeOf('/post/delete/{id}');

  expect(route).toMatchInlineSnapshot(`
    {
      "input": ZodObject {
        "_cached": null,
        "_def": {
          "catchall": ZodNever {
            "_def": {
              "typeName": "ZodNever",
            },
            "and": [Function],
            "array": [Function],
            "brand": [Function],
            "catch": [Function],
            "default": [Function],
            "describe": [Function],
            "isNullable": [Function],
            "isOptional": [Function],
            "nullable": [Function],
            "nullish": [Function],
            "optional": [Function],
            "or": [Function],
            "parse": [Function],
            "parseAsync": [Function],
            "pipe": [Function],
            "promise": [Function],
            "readonly": [Function],
            "refine": [Function],
            "refinement": [Function],
            "safeParse": [Function],
            "safeParseAsync": [Function],
            "spa": [Function],
            "superRefine": [Function],
            "transform": [Function],
          },
          "shape": [Function],
          "typeName": "ZodObject",
          "unknownKeys": "strip",
        },
        "and": [Function],
        "array": [Function],
        "augment": [Function],
        "brand": [Function],
        "catch": [Function],
        "default": [Function],
        "describe": [Function],
        "isNullable": [Function],
        "isOptional": [Function],
        "nonstrict": [Function],
        "nullable": [Function],
        "nullish": [Function],
        "optional": [Function],
        "or": [Function],
        "parse": [Function],
        "parseAsync": [Function],
        "pipe": [Function],
        "promise": [Function],
        "readonly": [Function],
        "refine": [Function],
        "refinement": [Function],
        "safeParse": [Function],
        "safeParseAsync": [Function],
        "spa": [Function],
        "superRefine": [Function],
        "transform": [Function],
      },
      "output": {
        "BAD_REQUEST": ZodObject {
          "_cached": null,
          "_def": {
            "catchall": ZodNever {
              "_def": {
                "typeName": "ZodNever",
              },
              "and": [Function],
              "array": [Function],
              "brand": [Function],
              "catch": [Function],
              "default": [Function],
              "describe": [Function],
              "isNullable": [Function],
              "isOptional": [Function],
              "nullable": [Function],
              "nullish": [Function],
              "optional": [Function],
              "or": [Function],
              "parse": [Function],
              "parseAsync": [Function],
              "pipe": [Function],
              "promise": [Function],
              "readonly": [Function],
              "refine": [Function],
              "refinement": [Function],
              "safeParse": [Function],
              "safeParseAsync": [Function],
              "spa": [Function],
              "superRefine": [Function],
              "transform": [Function],
            },
            "shape": [Function],
            "typeName": "ZodObject",
            "unknownKeys": "strip",
          },
          "and": [Function],
          "array": [Function],
          "augment": [Function],
          "brand": [Function],
          "catch": [Function],
          "default": [Function],
          "describe": [Function],
          "isNullable": [Function],
          "isOptional": [Function],
          "nonstrict": [Function],
          "nullable": [Function],
          "nullish": [Function],
          "optional": [Function],
          "or": [Function],
          "parse": [Function],
          "parseAsync": [Function],
          "pipe": [Function],
          "promise": [Function],
          "readonly": [Function],
          "refine": [Function],
          "refinement": [Function],
          "safeParse": [Function],
          "safeParseAsync": [Function],
          "spa": [Function],
          "superRefine": [Function],
          "transform": [Function],
        },
      },
      "path": "/post/delete/{id}",
      "type": "mutation",
    }
  `);
});
