/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BaseRouter {
  _def: {
    nodeType: 'router';
    routes: {
      greetings: {
        _def: {
          type: 'query';
          nodeType: 'route';
          argsSchema: string;
          outputSchema: string;
          description: 'My test query...';
        };
      };
    };
  };
}
