/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RootRouter {
  nodeType: 'router';
  routes: {
    test: RootTestRoute;
    test2: RootTest2Route;
    inner: RootInnerRouter;
  };
}
export interface RootTestRoute {
  type: 'mutation';
  nodeType: 'route';
  output: unknown;
}
export interface RootTest2Route {
  type: 'mutation';
  nodeType: 'route';
  input: {};
  output: {};
}
export interface RootInnerRouter {
  nodeType: 'router';
  routes: {
    test1: RootInnerTest1Route;
    test2: RootInnerTest2Route;
  };
}
export interface RootInnerTest1Route {
  type: 'query';
  nodeType: 'route';
  output: unknown;
}
export interface RootInnerTest2Route {
  type: 'query';
  nodeType: 'route';
  input: {};
  output: {};
}
