name: Build and test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    timeout-minutes: 10
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Run coverage
        run: yarn coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
